import { logout } from "@src/redux/slices/authSlice";
import { useAppDispatch } from "@src/redux/store";
import Link from "next/link";
import AdminNavbar from "./components/AdminNavbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="res-w py-5">
      <AdminNavbar />
      {children}
    </div>
  );
}
