import AdminNavbar from "./components/AdminNavbar";
import Wrapper from "@src/components/Wrapper/Wrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Wrapper>
      <div className=" px-2 py-5">
        <AdminNavbar />
        {children}
      </div>
    </Wrapper>
  );
}
